name: CI
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true
      - run: go mod download
      - run: go vet ./...
      - run: CGO_ENABLED=0 go build -o app .
      - run: go test -race -short ./...

