name: CI
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Download deps
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Build API
        run: CGO_ENABLED=0 go build -o app ./main

      - name: Test all packages
        run: go test -race -short ./...

